version: '3'
services:
  aic-manager:
    network_mode: host
    restart: always
    command: -m -n 1 -d drm
    privileged: true
    image: "mikeanthony/aic-manager:latest"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - ./workdir/media:/media:shared
      - ./workdir/ipc:/ipc
      - /usr/src:/usr/src
      - /lib/modules:/lib/modules
  android0:
    image: "mikeanthony/android:latest"
    privileged: true
    depends_on:
      - aic-manager
    command: "0"
    restart: always
    ports:
      - "5555:5555"
    mac_address: 8a:ca:58:b9:e9:51
    networks:
      android:
        ipv4_address: 172.100.0.2
    volumes:
      - ./workdir/app/installed:/oem/app:ro
      - ./workdir/ipc:/ipc
      - /dev/binderfs:/binderfs:rw
      - /dev/bus/usb:/dev/bus/usb
      - /dev/usb:/data/misc/usb:rw
      - ./workdir/ipc/config/ethernet/0:/data/misc/ethernet
      - ./workdir/data0:/data
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:

networks:
  android:
    labels:
      - "com.docker.network.bridge.name=br-android"
      - "com.docker.network.bridge.enable_icc=true"
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/16
