version: '3'
services:
  aic-manager:
    network_mode: host
    command: -d x11
    privileged: true
    image: "mikeanthony/aic-manager:latest"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - /root:/root
      - /root/aic/workdir/media:/media:shared
      - /root/aic/workdir/ipc:/ipc
      - /usr/src:/usr/src
      - /lib/modules:/lib/modules
  android0:
    privileged: true
    image: "mikeanthony/android:latest"
    ports:
      - "5555:5555"
    mac_address: 8a:ca:58:b9:e9:51
    networks:
      android:
        ipv4_address: 172.100.0.2
    volumes:
      - /root/aic/workdir/ipc/config/ethernet/0:/data/misc/ethernet
      - /root/aic/workdir/app/installed:/oem/app:ro
      - /root/aic/workdir/ipc:/ipc
      - /dev/binderfs:/binderfs:rw
      - /dev/bus/usb:/dev/bus/usb
      - /root/aic/workdir/data0:/data
networks:
  android:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/16
